# Generated by Django 5.0 on 2025-02-21 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mybodydata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(default=71.0)),
                ('height', models.FloatField(default=172.0)),
                ('smi', models.FloatField(default=28.0)),
                ('bodyfat', models.FloatField(default=18.0)),
                ('bodywater', models.FloatField(default=40.0)),
                ('bmr', models.FloatField()),
                ('bmi', models.FloatField(default=25)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bodydata', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-createdAt',),
            },
        ),
    ]
