# Generated by Django 5.0 on 2025-04-01 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mybodydata',
            options={'ordering': ('createdAt',)},
        ),
    ]
