# Generated by Django 5.0 on 2024-01-05 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='body',
            new_name='content',
        ),
        migrations.AddField(
            model_name='post',
            name='coverImg',
            field=models.ImageField(blank=True, upload_to='posts/', verbose_name='Post cover image'),
        ),
    ]
