# Generated by Django 5.0 on 2024-01-05 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_rename_body_post_content_post_coverimg'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ('-createdAt',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-createdAt',)},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='updated_at',
            new_name='updatedAt',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='updated_at',
            new_name='updatedAt',
        ),
    ]
