# Generated by Django 5.0 on 2024-01-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_image'),
        ('posts', '0004_post_featured'),
    ]

    operations = [
    ]
