# Generated by Django 5.0 on 2024-01-08 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_post_image_post_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='views',
            new_name='view',
        ),
    ]
