# Generated by Django 5.0 on 2025-09-05 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstop',
            name='stationId',
            field=models.IntegerField(unique=True),
        ),
    ]
